server:
  port: 2000
  
spring:
   application:
      name: user-service
   datasource:
      url: jdbc:postgresql://localhost:5432/db_micropayment
      username: postgres
      password: cobacoba23
      driverClassName: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: update
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1000/eureka/